### ISSUE TITLE
Parsing: confusion between Flow typecast and parenless if condition

### ISSUE THREAD

**Issue by plexigras** [wcjohnson/lightscript#22]
```js
xor = (x, y) => (x or y) and not (x and y)
if x ~xor! y: z
```
trows `unknown: Paren-free test expressions must be followed by braces or a colon. (3:15)`

```js
if x ~xor(y): z
if (x ~xor! y): z
```
both work

[here](https://wcjohnson.github.io/lscdiag/?v=1&s=eMOafVBNT8ODMAzDvSvDgScmw7VQw7EhwqDDksOQEGfDuAPDncKEwrzDlMOtMsK5ScKVOlLCu8Kqw7x2wpzCiSvDpMKSZ8Onw6XCvWcvw5DCuklSwqQRwqoFwr56HMOywr3Dm8O1JMOYwqBgwq7DrMO5wqnCvMKbexdKPcO3wo8PwpfDqcOlw7IcbTxDJTHDkVrDvMOHWGAMKVrDisKIRwsVTCHCmsKtwrnCnQozb8OMw7ZVwpHDkcKOYsO0wo3DsUFyI8ODecKzw7d7w69aM8KZb8O9c2PDpsOKXEDDncKSw4tiwoJHw41cwpdFeShgJCYrw5R8woZGwp18YsOOwqnCgm9dd8KdIMO0woNjworDqsOOKDQKFMOQEsO-w45dw4PDgGjDqRTCuMKhw7gWwrtRX8KPw6jCu3dkBhUPwoPCuMOgwq8LGlDChMKiw79AwrEnw6dVGxpqMcKxw6RcA8Knw45lXn1YV8Ktw5nCqcKRwqrDv8K9HcOlw70Aw5LDiH_Cog#) the example in lscdiag

**Comment by wcjohnson** [comment]
OK, I figured out what's happening here.

Flow interprets an expression of the form `a: b` as a typecast of the value `a` into the type `b`. So what's happening here is:
```
x~xor! y: z
```
is being parsed as
```
xor(x, y: z)
```
where `y: z` is a flow typecast of y into type z.

This is actually the correct behavior, so I can't call this a bug. However, there may still be room for a design change here re: the Flow grammar. One possibility would be to require parens around Flow typecasts.

I'm not ready to take a specific action yet but I am leaving the issue open for further discussion of what change if any should be made here.

**Comment by wcjohnson** [comment]
Relevant Flow parse code:

https://github.com/wcjohnson/babylon-lightscript/blob/ffb7ddb07eda14deb9bf8c4b7f2507c26d80e04f/src/plugins/flow.js#L1105

**Comment by wcjohnson** [comment]
Workaround is to specify `disableFlow` to disable Flow typing:

https://wcjohnson.github.io/lscdiag/?v=1&s=eMOafcKPw4Fqw4MwEER_RcOVJRc3NTFtw4AnQ8Khw4fDvkASw4pawpbDrU3DlsKSwpBWScKKUcK_wr1Sw6k5e8OZHRh2w57CrHLDhDtHwq_Cg2xXw7nCtcKAK8K7w6sWw40wAENRw6rDnFx3w5_DvjLDlnnCmsOLw5vDq8Kew7bDoMKaK8OLwpZ9w5TCqXrDpFhlwrDDkStdLgpKwrZyE8KDFsKdw4XDicObw6heCMKnwpnCg8Oyw6hYw5zCkGfDkcKDwpnDnsKBwqgSAwbDqEl_wpDCvW3CjsOmaHAUw7BzwrfDvknDtMKtUDLDp0YsbxnDukx_wqjCq8O6VMOJwqBJK8OWw4PCpx1ywqbCiUTChcOPwpoRwqfCvy52cUjDmmfCjn_Cgm7Ct23CtsO1M8KQwptBwqbClMOdwoQhwoMfHsK0OsKlw7QLwoYXaMOc#

**Comment by wcjohnson** [comment]
Action here is going to be to require parens around Flow typecasts. Apparently the Flow grammar already specifies this but Babylon isn't enforcing it.

**Comment by wcjohnson** [comment]
This will be fixed in alpha.7!
