### ISSUE TITLE
Await arrow as first bang call arg doesn't parse

### ISSUE THREAD

**Issue by plexigras** [wcjohnson/lightscript#58]
[lscdiag example](https://wcjohnson.github.io/lscdiag/?v=1&s=eMOawp3CkcOdSsOEMBDChV_CpTtXLsK0wrXDm0XDlCJSw7DDnhdYF0nDkmnCiE7Ck8KaH8OYwqXDtMOdTVbDr8KqRcOMTcKSwpMzJ8OzJRPDtMOqw6TCg0UHw40Ewq8DG8OTw5zCtgN6w5Yxw4_Dkk7CvMOdw5fDnjsrwqo4w7bDvcONwrk-w5PDiMOeJcKHw4bDm8KAw7nDhRAkwr8bw6LDuS4Zw5jCrcO8w6DCg1VfwoY5X8KLwpjDgMKZYAXCphU5AQ0Uw5fCjy86w4vChMORw44QwpZkw6QmeyjCssOTUsOcRBVifFDCqcOaMx4pDlVeHXNwSCg8dsOPwqbCi8OROhDCpTbCjMOuwpXCvDDCmWFUwoQ2XmfClMK0JsKMw63CvsKsw4rCqhgtQg49wrLDr0c5AGdaPjEiOMOOw7Mqw6tfSMKuEsOIdiEmwpDDrQ8kwrsFScO9T8KMw5h8wqwkw6V8YsO6w70_w5YIY8OGJ0ItwrXDvQ#)

**Comment by wcjohnson** [comment]
Bug; solution is `<-` needs to be `startsExpr` -- will be fixed in next release

**Comment by wcjohnson** [comment]
Fixed in beta.6
