### ISSUE TITLE
Syntax proposals/brainstorming for object value assignment

### ISSUE THREAD

**Issue by wcjohnson** [wcjohnson/lightscript#71]
A common pattern involves checking if an object has an own property, creating it if not, then mutating its value in some way:

```js
    let delta = this[deltaSymbol]
    if not delta: this[deltaSymbol] = now delta = Object.create(null)
    delta[key] = prevVal
```

This pattern appears to be pervasive in the ecosystem as well as overly verbose, so it might be worthwhile to design an improved syntax. Brainstorming in this thread about what that might be.

Ideally this should support chaining:

```js
mapOfSymbol = Symbol.for("ephraim.mapOfType")
export mapOf(T1, T2) ->
  now T1 = typeFrom(T1)
  now T2 = typeFrom(T2)
  cached = T1[mapOfSymbol]?[T2.typeIdentity]
  if cached: return cached
  // No cached map type, create
  T1[mapOfSymbol] = T1[mapOfSymbol] or {}
  T1[mapOfSymbol][T2.typeIdentity] = new MapType(T1, T2)
```

**Comment by plexigras** [comment]
you mean something like `a?.b?.c = d`?

```js
a = a || {}
a.b = a.b || {}
a.b.c = d
```

**Comment by plexigras** [comment]
`x = (a?.b?.c = d)` could compile to

```
a = a || {}
a.b = a.b || {}
x = a.b.c = a.b.c || d
```

or you could add a new operator like `|=` or `?=` but i'm not sure i like that.

**Comment by wcjohnson** [comment]
The semantics of the `?.` operator are being standardized by JS and can't be changed. It would have to be a new operator.

**Comment by plexigras** [comment]
well then i vote for `?=` over `|=`

**Comment by rattrayalex** [comment]
Is TC39 working on an `||=`? I thought they were...

**Comment by wcjohnson** [comment]
There is a stage-1 logical assignment operator proposal, and Babel has a transform for it.

In its current state it just forbids optional chaining on the LHS: [Babel repl](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=IYfg2gRgugBAPnAvDAxgKA0A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.0.0&envVersion=)

In any case `||=` is basically covering the same ground and is already in TC39 so I don't plan on taking any immediate action re syntax here.

**Comment by wcjohnson** [comment]
I've enabled the `||=` via babel's `transform-logical-assignment` and tested it in my own code. I find it sufficiently covers these use cases and is already in TC39, so will close this.
