### ISSUE TITLE
Possibly incorrect function scoping

### ISSUE THREAD

**Issue by wcjohnson** [wcjohnson/lightscript#98]
In ES2015, functions are block scoped, and `@babel/core` 7.x treats them as such throughout. However, in LightScript we have special case code that is hoisting function declarations to function scope, overriding these semantics.

https://github.com/wcjohnson/lightscript-transform/blob/6e1e7e524045a50b366a060038d0d51a2085bfca/src/transforms/functions.lsc#L7

This code dates back to LightScript 0.5.9:

https://github.com/lightscript/babel-plugin-lightscript/blob/eb650acf69a17f0e4af9ce10a4c1bdeacec1e9e7/src/index.js#L1141

I am not sure this behavior is correct; LightScript should probably be treating functions as block scoped and shouldn't respect old JS semantics.

**Comment by rattrayalex** [comment]
Ah. Sounds like a bug, I think when I implemented that I wasn't thinking very deeply about it. Good catch!
